doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            client1:
                url: '%env(resolve:CLIENT1_DATABASE_URL)%'
        default_connection: default
    orm:
        default_entity_manager: default
        controller_resolver:
            auto_mapping: true

        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            client1:
                connection: client1
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Client1:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/WhiteLabel/Entity/Client1'
                        prefix: 'App\WhiteLabel\Entity\Client1'
                        alias: Client1
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
            controller_resolver:
                auto_mapping: true  # Ajout de cette ligne

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
