vich_uploader:
    db_driver: orm

    mappings:
       cv_expert:
           uri_prefix: '%cv_expert%'
           upload_destination: '%kernel.project_dir%/public%cv_expert%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false

       medias_prestation:
           uri_prefix: '%medias_prestation%'
           upload_destination: '%kernel.project_dir%/public%medias_prestation%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false

       logo_company:
           uri_prefix: '%logo_company%'
           upload_destination: '%kernel.project_dir%/public%logo_company%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false

       products:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       places:
           uri_prefix: /images/places
           upload_destination: '%kernel.project_dir%/public/images/places'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
       blogs:
           uri_prefix: /images/blogs
           upload_destination: '%kernel.project_dir%/public/images/blogs'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
